import FAQS from "./FAQ"
import ForgetPassword from "./ForgetPassword"
import ResetPassword from "./ResetPassword"
import Login from "./Login"
import Register from "./Register"
import Privacy from "./Privacy"
import Terms from "./Terms"
import User from "./User"
import Home from "./Home"
import ProtectedRouteUser from "./protectedRoutesUser"
import About from "./About"
import Properties from "./Properties"
import SingleProperty from "./SingleProperty"
import Cart from "./Cart"
import OrderSuccess from "./OrderSuccess"
import OrderFailure from "./OrderFailure"
export {FAQS,ForgetPassword,ResetPassword,Login,Register,Privacy,Terms,User,Home,ProtectedRouteUser,About,Properties,SingleProperty,Cart,OrderFailure,OrderSuccess}